name: make snek
on:
  workflow_dispatch:
jobs:
  build:
    name: make_snek
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snek.svg?palette=github-dark&color_snake=#e06c9f&color_dots=#14141e,#7cb9db,#7cb9db,#7ccbd8,#7cded5
      - uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
