name: make snek
on:
  schedule: # execute every 6 hours
    - cron: "* */6 * * *"
  workflow_dispatch:
jobs:
  build:
    name: make_snek
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          #
          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:     A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots:  Coma separated list of dots color.
          #                 The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                 Exactly 5 colors are expected.
          #  dist/snek.svg?palette=github-dark&color_snake=#7878FF&color_dots=#14141E,#00321E,#004628,#147832,#00C850
          outputs: |
            dist/snek.svg?palette=github-dark&color_snake=#e06c9f&color_dots=#14141e,#7cb9db,#7cb9db,#7ccbd8,#7cded5
  
      - uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
